/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;
import utils.Utils;


public class VistaDepositoDinero extends javax.swing.JFrame {

    /**
     * Creates new form VistaPantallaPrincipal
     */
    public VistaDepositoDinero() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.campoMuestreoSaldo.setText(Double.toString(Utils.dineroUsuario));
              
    }
    
    public void agregarListener(ActionListener a){
        this.btnDepositar.addActionListener(a);
    }
    
    public void actualizarPantalla(){
        this.campoMuestreoSaldo.setText(Double.toString(Utils.dineroUsuario));
        this.campoDeposito.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoDeposito = new javax.swing.JTextField();
        btnDepositar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoMuestreoSaldo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoMuestreoSaldo1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(672, 465));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(672, 465));
        jPanel1.setMinimumSize(new java.awt.Dimension(672, 465));
        jPanel1.setPreferredSize(new java.awt.Dimension(672, 465));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SALDO DISPONIBLE:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 80, 350, 70);

        campoDeposito.setBackground(new java.awt.Color(255, 255, 153));
        campoDeposito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(campoDeposito);
        campoDeposito.setBounds(240, 240, 200, 40);

        btnDepositar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDepositar.setText("DEPOSITAR");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDepositar);
        btnDepositar.setBounds(250, 290, 160, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("$");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 240, 40, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INGRESA EL MONTO A DEPOSITAR: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 180, 460, 70);

        campoMuestreoSaldo.setBackground(new java.awt.Color(0, 0, 0));
        campoMuestreoSaldo.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        campoMuestreoSaldo.setForeground(new java.awt.Color(0, 255, 0));
        campoMuestreoSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoMuestreoSaldo.setOpaque(true);
        jPanel1.add(campoMuestreoSaldo);
        campoMuestreoSaldo.setBounds(360, 100, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/wallpaper_atm.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(672, 465));
        jLabel1.setMinimumSize(new java.awt.Dimension(672, 465));
        jLabel1.setPreferredSize(new java.awt.Dimension(672, 465));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 470);

        campoMuestreoSaldo1.setBackground(new java.awt.Color(0, 0, 0));
        campoMuestreoSaldo1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        campoMuestreoSaldo1.setForeground(new java.awt.Color(0, 255, 0));
        campoMuestreoSaldo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoMuestreoSaldo1.setOpaque(true);
        jPanel1.add(campoMuestreoSaldo1);
        campoMuestreoSaldo1.setBounds(360, 100, 180, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepositarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDepositoDinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDepositoDinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDepositoDinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDepositoDinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaDepositoDinero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDepositar;
    public javax.swing.JTextField campoDeposito;
    private javax.swing.JLabel campoMuestreoSaldo;
    private javax.swing.JLabel campoMuestreoSaldo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
